### PR TITLE
Drop py27 py34 support

### PR DESCRIPTION
**Pull request by s-weigand**
Since more an more tests have failed, due to dropped support of python 2.7 and 3.4 in other libraries (see: #51, #52, #53, #54), the support for those versions should be dropped aswell.

**Changes**:
- Dropped legacy code and tests
- Updated history
- Added instructions for users to pin ``pytest_localftpserver==0.6.0`` if they need py27/34 support

Before this is merged there should be a release as mentioned in #53, so users also get the FTPs server for py27/34.

Also tell me if you want to go with a different scheme for the version numbers as I proposed in ``HISTORY. rst``

### CODE REVIEW

**Comment by s-weigand** [comment]
Hmmmm I see there was no 0.6.0 Release for the py27 and py34 people, so having that on the frontpage is pointless :cry:

**Comment by oz123** [comment]
I'll make a release later this week.

**Comment by s-weigand** [comment]
Yeah but like that the py27 and py34 people wont have the FTPS server + the info about the 0.6.0 release (which will also be on PyPi), would be false.
Possible solutions:

1. Change the 0.6.0 to 0.5.1 (no FTPS for old python versions)
2. Rewind to before this merge -> release 0.6.0 -> remerge -> release 1.0.0

Or maybe I just misunderstood your release plan, since I use, Continuous Deployment to release my stuff.

**Comment by oz123** [comment]
I can make release for 0.6.0 based on the code before this merge. It's a bit of git fu, but it's not magic.

**Pull request merged**
